[libdefaults]
   default_realm = INTERN.SALIGER.ME
   dns_lookup_realm = false
   dns_lookup_kdc = true
   default_ccache_name = /run/user/%{uid}/krb5cc

[realms]
   INTERN.SALIGER.ME = {
      kdc = DC1.INTERN.SALIGER.ME
      default_domain = INTERN.SALIGER.ME
      admin_server = DC1.INTERN.SALIGER.ME
   }
   INTERN = {
      kdc = DC1.INTERN.SALIGER.ME
      default_domain = INTERN.SALIGER.ME
      admin_server = DC1.INTERN.SALIGER.ME
   }

[domain_realm]
    .intern.saliger.me = INTERN.SALIGER.ME
    intern.saliger.me = INTERN.SALIGER.ME

[appdefaults]
    pam = {
        ticket_lifetime = 1d
        renew_lifetime = 1d
        forwardable = true
        proxiable = false
        minimum_uid = 1
    }
